### ISSUE TITLE
Failure to run coverage with ava when the path has a space

### ISSUE THREAD

**Issue by brogdonm** [istanbuljs/nyc#784] opened 2018-02-23 07:52 UTC
## Expected Behavior
When running (`npm run test:cov`) on a windows box with a home path of `C:\Users\First Last\repo-name` would expect the same type of behavior when the path *does not* have a space in it.

## Observed Behavior
Currently, when I try to run I get an error on windows `'C:\Users\First' is not recognized as an internal or external command`, indicating the spaces are not escaped correctly. 

## Bonus Points! Code (or Repository) that Reproduces Issue
The following is an excerpt from our package.json file:

```
"scripts": {
      "test": "cross-env BABEL_ENV=test ava",
      "test:cov": "nyc npm run test && nyc report --reporter=lcov"
},
  "ava": {
    "require": "babel-register",
    "babel": "inherit"
  },
  "nyc": {
    "sourceMap": false,
    "instrument": false
  },
```

## Forensic Information

Windows 10 x64 machine
`CWD` = C:\Users\Michael Brogdon\repository-name

Version info:

```
node - v8.9.4
npm - 5.6.0
nyc - 11.4.0
ava - 0.24.0

```

**Comment by devMYC** [comment] 2018-03-09 03:01
Also having a problem with `include: [ "__tests__/**/*.js" ]` in `.nycrc` result in empty coverage report. And it works fine without the underscores in the file path.

**Comment by nicolaspfernandes** [comment] 2018-03-26 14:55
Have you found a solution for this issue? I'm getting it today.

**Comment by brogdonm** [comment] 2018-03-26 17:39
@nicolaspfernandes I haven't found a solution yet. Right now I have just worked around it by checking out in a path that does not have spaces.

**Comment by JeKachan** [comment] 2018-04-18 14:27
The similar issue with path, but with testing child processes via require('child_process').spawn

**Comment by dagerikhl** [comment] 2018-05-22 19:37
Facing the same issue when using a user with a space in the name, getting `'C:\Users\Dag' is not recognized as an internal or external command, operable program or batch file.` when running `nyc npm test --color`.

The project itself is not placed on the path with a space, it's placed on another drive. But for some reason nyc accesses the C:\ path for something.

Using Windows 7 v. 6.1.7601 SP1 Build 7601 with Git Bash for Windows v. GNU bash, version 4.3.42(5)-release (x86_64-pc-msys). Same error found with CMD and PowerShell as well.

No issue on my other computer running Windows 10, but that one doesn't have any spaces in the username.

**Comment by genius8901** [comment] 2018-11-14 17:29
having the same problem. the logs shows:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Shaked Eyal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'coverage' ]
2 info using npm@6.1.0
3 info using node@v10.13.0
4 verbose run-script [ 'precoverage', 'coverage', 'postcoverage' ]
5 info lifecycle sample-project@1.0.0~precoverage: sample-project@1.0.0
6 info lifecycle sample-project@1.0.0~coverage: sample-project@1.0.0
7 verbose lifecycle sample-project@1.0.0~coverage: unsafe-perm in lifecycle true
8 verbose lifecycle sample-project@1.0.0~coverage: PATH: C:\Users\Shaked Eyal\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\genius8901-sqe-workshop-2018-exercise-1\node_modules\.bin;C:\Python37\;C:\Python37\Scripts\;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\MinGW\bin;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\Program Files (x86)\Mercurial;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\LLVM\bin;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin;C:\Users\Shaked Eyal\AppData\Local\Microsoft\WindowsApps;C:\Users\Shaked Eyal\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Shaked Eyal\AppData\Local\GitHubDesktop\bin;C:\Users\Shaked Eyal\AppData\Roaming\npm
9 verbose lifecycle sample-project@1.0.0~coverage: CWD: C:\genius8901-sqe-workshop-2018-exercise-1
10 silly lifecycle sample-project@1.0.0~coverage: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=coverage nyc --reporter=json-summary npm run test' ]
11 silly lifecycle sample-project@1.0.0~coverage: Returned: code: 1  signal: null
12 info lifecycle sample-project@1.0.0~coverage: Failed to exec coverage script
13 verbose stack Error: sample-project@1.0.0 coverage: `cross-env NODE_ENV=coverage nyc --reporter=json-summary npm run test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Shaked Eyal\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Shaked Eyal\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid sample-project@1.0.0
15 verbose cwd C:\genius8901-sqe-workshop-2018-exercise-1
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shaked Eyal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "coverage"
18 verbose node v10.13.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error sample-project@1.0.0 coverage: `cross-env NODE_ENV=coverage nyc --reporter=json-summary npm run test`
22 error Exit status 1
23 error Failed at the sample-project@1.0.0 coverage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by genius8901** [comment] 2018-11-14 17:30
I have the same problem. The logs are:
> 12 info lifecycle sample-project@1.0.0~coverage: Failed to exec coverage script
13 verbose stack Error: sample-project@1.0.0 coverage: `cross-env NODE_ENV=coverage nyc --reporter=json-summary npm run test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Shaked Eyal\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Shaked Eyal\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid sample-project@1.0.0
15 verbose cwd C:\genius8901-sqe-workshop-2018-exercise-1
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shaked Eyal\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "coverage"
18 verbose node v10.13.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error sample-project@1.0.0 coverage: `cross-env NODE_ENV=coverage nyc --reporter=json-summary npm run test`
22 error Exit status 1
23 error Failed at the sample-project@1.0.0 coverage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by genius8901** [comment] 2018-12-09 15:44
I am looking into it

**Comment by pushkin-** [comment] 2019-02-13 20:29
"Further activity" so this issue stays open

**Comment by MarcusPope** [comment] 2019-02-22 04:24
The issue is caused by node's os.homedir() function.  The particular line to fix is here: 

https://github.com/istanbuljs/nyc/blob/master/bin/nyc.js#L47

I would recommend using os.tmpdir() instead which automatically uses the 8.3 short name format (https://en.wikipedia.org/wiki/8.3_filename)
 
For those who need to get past this issue before a fix, you can assign the env var `SPAWN_WRAP_SHIM_ROOT` to some path without spaces, or use the tilde short name for a directory with spaces eg: C:\Program~1

Hope that helps!

**Comment by coreyfarrell** [comment] 2019-02-22 09:48
This seems to be a non-issue on Linux platforms?  I just did the following:
```
mkdir 'this is a test'
cd 'this is a test'
npm init
npm i -D nyc
SPAWN_WRAP_SHIM_ROOT=$PWD npx nyc ls -lha
```
This correctly showed a `.node-spawn-wrap-*` folder.  I also created a basic `mytest.js`:
```js
#!/usr/bin/env node
console.log('hello');
```
Then ran:
```
chmod +x mytest.js
SPAWN_WRAP_SHIM_ROOT=$PWD npx nyc ./mytest.js
```
And this worked.  So if this is a Windows specific issue maybe it could be fixed within spawn-wrap?  If we need to switch from `os.homedir()` to `os.tmpdir()` I'd rather do it for affected platforms only.  I'm concerned that on some Linux systems `os.tmpdir()` might be on a `noexec` mount or maybe SELinux might interfere.

**Comment by MarcusPope** [comment] 2019-06-20 16:24
I agree with @coreyfarrell 's concerns and after doing a bit more research on the issue it appears that even tmpdir() wouldn't fix the problem because it is merely a pass-thru for whatever env var is already set (and tmpdir just happened to be in 8.3 format on my machine) (ref: [Node Issue 17586](https://github.com/nodejs/node/issues/17586))

I think the best course is to update the readme with notes about resolving this error with an env override for the user's home directory _when_ it has either spaces or special characters in the username segment.  I'll drop a PR in a bit.

**Closed** 2019-07-09 19:06 UTC
Labels: Great First Contribution, help wanted

**Comment by brogdonm** [comment] 2019-07-09 20:08
Thanks ya'll!!
