### ISSUE TITLE
Incorrect release version on npm

### ISSUE THREAD

**Issue by jalutz** [istanbuljs/nyc#740] opened 2017-12-07 15:38 UTC
I wasn't sure where else to put this, but noticed 11.4 was released, but it still says 11.3 is the latest on the npm page. Led to a bit of confusion when running "npm outdated" as it said we were a version ahead of the latest possible version!

**Comment by JaKXz** [comment] 2017-12-08 01:46
This is a duplicate of #735 and #739.

**Closed by JaKXz** 2017-12-08 01:46 UTC
