### ISSUE TITLE
nyc-config-babel not working (Error: ENOENT)

### ISSUE THREAD

**Issue by hbarcelos** [istanbuljs/nyc#588] opened 2017-06-01 19:45 UTC
## Expected Behavior

`nyc` should run.

## Observed Behavior

Error:
```
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '<project-root>/@istanbuljs/nyc-config-babel'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at applyExtends (/usr/lib/node_modules/nyc/node_modules/yargs/lib/apply-extends.js:29:35)
    at Object.Yargs.self.config (/usr/lib/node_modules/nyc/node_modules/yargs/yargs.js:308:13)
    at Object.Config.loadConfig (/usr/lib/node_modules/nyc/lib/config-util.js:34:24)
    at Object.<anonymous> (/usr/lib/node_modules/nyc/bin/nyc.js:23:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```
It seems like the script is missing the `node_modules` subdirectory.

### package.json

```json
  "devDependencies": {
    "@istanbuljs/nyc-config-babel": "^1.2.2",
    "ava": "^0.19.1",
    "babel": "^6.23.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-syntax-class-properties": "^6.13.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-preset-env": "^1.5.1",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-node": "^4.2.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "nyc": "^11.0.1"
  }
```
### Environment
- OS: Ubuntu 14.04
- More info: https://gist.github.com/hbarcelos/5ef5f21af7259d9b91b04b0d12594c71

**Comment by bcoe** [comment] 2017-06-03 00:10
@hbarcelos if possible, could you share the project that's having this problem so that I can debug.

**Comment by hbarcelos** [comment] 2017-06-04 13:22
@bcoe unfortunately the project is not open-source, so I cannot share it with you.

**Comment by bcoe** [comment] 2017-07-30 19:08
@hbarcelos closing this issue for now, because I don't have enough information to reproduce the issue; If you have some time, please provide a minimal reproduction for this issue in a repository you can share, and I'll happily revisit this issue.

**Closed by bcoe** 2017-07-30 19:08 UTC

**Comment by umeshp7** [comment] 2019-05-16 19:13
I updated from 11.4.1 to 14.1.1 and I started getting this error. 
The tests are passing but fails at the end to access .coverage file in my case. 
Error: ENOENT: no such file or directory, open '<path>/.coverage/processinfo/401c82b7-f2dd-44d1-bd53-6258e36577e1.json'
401c82b7-f2dd-44d1-bd53-6258e36577e1.json This file is not in side processinfo, its inface in .coverage folder.

**Comment by coreyfarrell** [comment] 2019-05-17 13:16
@umeshp7 you are experiencing a completely different issue.  Please post your own bug report including all required information.
