### ISSUE TITLE
nyc meteor support

### ISSUE THREAD

**Issue by hexsprite** [istanbuljs/nyc#648] opened 2017-08-15 22:38 UTC
## Expected Behavior

`nyc meteor test` should produce a coverage report

## Observed Behavior

`nyc` can't seem to retrieve the coverage from the test. However if I call the node executable directly instead of using the meteor wrapper script it works fine. Eg:

`$NODE $METEORJS test`

I believe this is probably something that will need to be fixed in Meteor JS itself but I'm hoping someone from the nyc project can point me in the right direction as to what the wrapper script might be doing to prevent nyc from working correctly.

Perhaps certain environment variables need to be preserved ?

**Comment by bcoe** [comment] 2017-09-16 19:32
@hexsprite 👋 hey. This is an interesting one, I'd definitely expect that `node meteor` would also fail to return coverage.

I would love some help digging into this one, as I myself am not a Meteor user. Where I would start would be to look at if there's any difference in how meteor is executed if it's run with `node` vs. relying on the shebang.

If you feel like collaborating on debugging this issue, there's a community slack you can join:

http://devtoolscommunity.herokuapp.com/

**Comment by hexsprite** [comment] 2017-09-16 23:38
Hey thanks @bcoe, I joined Slack and I'll reach out to you

To document the problem further here's an analysis of the flow of execution.

A user runs the Meteor script in their shell like so:

`$ meteor test <test args etc>`

Meteor script is here:

https://github.com/meteor/meteor/blob/devel/scripts/admin/launch-meteor

It's basically a bootstrapping bash script that will locate and possibly download
Meteor.

Once done it will exec and run the actual Meteor bash script:

```bash
# truncated to last line...
exec "$METEOR_WAREHOUSE_DIR/meteor" "$@"
```

This is the meteor bash script:

https://github.com/meteor/meteor/blob/devel/meteor

This script actually invokes Node itself and invokes the Meteor NodeJS code:

```bash
# truncated to last line...
exec "$DEV_BUNDLE/bin/node" \
     --expose-gc \
     ${TOOL_NODE_FLAGS} \
"$METEOR" "$@"
```

I was able to get NYC working with Meteor by essentially invoking the last line
of this script.

**Comment by coreyfarrell** [comment] 2019-03-07 16:01
I suspect the issues you were having may have been related to `spawn-wrapper` interactions with your custom script.  Is this still an issue with the current version of nyc?  Last activity on this issue was quite a while ago and `spawn-wrap` has gotten some updates.

**Comment by hexsprite** [comment] 2019-03-07 23:08
The testing tools I'm using (`meterotesting:mocha` and `lmieulet:meteor-coverage`) ended up going another route to integrate Instanbul. So I'm not able to test this further at this time.

**Comment by coreyfarrell** [comment] 2019-03-07 23:27
Thanks for getting back to me.  I'm going to close this issue since we won't be able to make any progress without reproducing against the current version.  If the situation changes let us know.

**Closed by coreyfarrell** 2019-03-07 23:27 UTC
Labels: question, triaged

**Comment by mohitsati14** [comment] 2019-03-27 08:45
I can verify in the latest version also, it is not working

**Comment by coreyfarrell** [comment] 2019-03-27 11:04
@mohitsati14 please open a new issue and provide all required information including a reproduction against current versions.
