### ISSUE TITLE
Link line coverage back to test cases that hit those lines

### ISSUE THREAD

**Issue by lannonbr** [istanbuljs/nyc#933] opened 2018-10-30 18:13 UTC
![Image from readme on line coverage](https://raw.githubusercontent.com/istanbuljs/nyc/master/screen2.png)

In nyc's HTML output, you can see that a particular line is hit the number of times through the tests. Would there be some way to be able to click on the hit count in the gutter of a particular line and be able to see what tests hit said line of code?

I would at least like some feature that even just listed the file location and test name so you can easily go find it.

**Comment by JaKXz** [comment] 2019-01-23 06:07
closing as a duplicate of #633. Please correct me if I'm wrong!

**Closed by JaKXz** 2019-01-23 06:07 UTC
Labels: wontfix
