### ISSUE TITLE
Coverage is not displayed properly

### ISSUE THREAD

**Issue by repinvv** [istanbuljs/nyc#975] opened 2019-01-21 22:42 UTC
## Repository url: https://gitlab.com/vlr/tslib-seed/-/jobs/148945040
There is a gitlab CI configured where the defect reproduces

## Expected Behavior
coverage displayed at the end of test run

## Observed Behavior
Branch coverage is displayed as 100%, The rest of metrics are displayed as 0%

**Operating System:** Win7, Win10, Ubuntu on windows, Debian.
Issue does not seem related to OS
**Environment Information:**
![nodev](https://user-images.githubusercontent.com/1575441/51501660-ec416080-1de3-11e9-85b4-f9ce42319c3f.PNG)

Issue seem to be related to when nyc package was installed. In our workplace environment, on the same OS, same node and npm versions it did work for one developer who installed it few months ago and did not work for developer who installed it recently.
Also on my home pc it was working, but when i removed and reinstalled global nyc package of the same version, it did break. And i still have nyc of the same version installed a while ago on Ubuntu on windows.
Here is the situation i have on my pc now - the same repository, same packages, it works in bash and does not work in cmd. Deleting node_modules and package lock and running npm i on either system does not change it.
![nyc](https://user-images.githubusercontent.com/1575441/51501491-252d0580-1de3-11e9-9022-e8b6b94a1690.PNG)

Can't be sure, but symptoms are as if one of nyc dependencies was recently updated which broken the scenario.

**Comment by coreyfarrell** [comment] 2019-01-24 16:16
Appears so.  node.js 11.7.0 cannot currently run mocha under nyc.  My understanding is this will be fixed by both node.js 11.8.0 and the next release of mocha.  Nothing can be done from the nyc side.

**Comment by repinvv** [comment] 2019-01-24 16:17
Could be the same issue, but output does not look the same, in that other issue no files are listed. In my case all js files are listed with zero coverage.
And  issue reproduces with node 10

**Comment by coreyfarrell** [comment] 2019-01-24 16:22
Thanks I didn't catch that, reopened.

**Comment by bcoe** [comment] 2019-01-26 02:19
could you confirm that this is fixed in https://nodejs.org/en/blog/release/v11.8.0/

**Comment by bcoe** [comment] 2019-01-26 02:20
EDIT: just read that this reproduces in 10.

**Comment by repinvv** [comment] 2019-01-29 14:01
Do not know what changed, but defect does not seem to reproduce anymore in that gitlab ci environment. NYC version is the same, 13.1.0

**Comment by coreyfarrell** [comment] 2019-01-29 14:26
@repinvv potentially a dependency or node.js has been updated?  Difficult to say but I'm going to close this issue since you say it's no longer happening.  If it resurfaces please let us know.

**Closed by coreyfarrell** 2019-01-29 14:26 UTC
