### ISSUE TITLE
Run Coverage on Watch

### ISSUE THREAD

**Issue by dschinkel** [istanbuljs/nyc#767] opened 2018-01-22 22:11 UTC
Is there a way to get code coverage to run even when watch is enabled for mocha?

`"test:mocha": "BABEL_ENV=test nyc mocha ./src/test/mocha-webpack-compiler.js -w -r babel-core/register --recursive ./src/test/isolated-unit/**/*.spec.js -t $test-isolated-timeout"`

right now the behavior is the tests run, watch is enabled so my tests sit and wait for changes.  That means coverage isn't run unless I stop the tests from running, then coverage kicks in and spits out the results.  I don't want that I want to see coverage right after my tests run every time, even during watch.

**Comment by JaKXz** [comment] 2018-02-04 09:27
This looks like a duplicate of #310 - if there's something I'm missing please feel free to reopen but otherwise we can contain the discussion there :)

**Closed by JaKXz** 2018-02-04 09:27 UTC
