### ISSUE TITLE
Node API usage

### ISSUE THREAD

**Issue by demurgos** [istanbuljs/nyc#720] opened 2017-11-13 15:59 UTC
Hi,
I am trying to integrate coverage support to my gulp tasks. It seems that there is no existing gulp plugin so I want to write my own solution.

Is `nyc` intended to be used as a Node library? The README only says that it is a command line interface and there is no documentation at all about how to use it from Node.

If `nyc` is not intended to be used from Node, should I spawn it as a child process or use another library? (Istanbul? Which one?)

**Comment by JaKXz** [comment] 2017-11-16 05:11
Hi @demurgos, I believe the Jest team has done a good job making an example of using the underlying istanbuljs/istanbuljs libraries. You could start here: https://github.com/facebook/jest/blob/77744a2/scripts/mapCoverage.js

I believe that node-tap also uses nyc under the hood to produce coverage reports: https://github.com/tapjs/node-tap

This is a duplicate of #499 & sort of #693.

Curious if @bcoe or anyone in @istanbuljs/nyc has strong interest in documenting a programmatic API.

**Comment by demurgos** [comment] 2017-11-16 12:07
Thanks.
I'll take a closer look at the examples you provided. My issue about using Istambul instead of nyc is that nyc seems to be more than "just a cli" but also a higher level layer.

**Comment by bcoe** [comment] 2017-11-27 04:44
@demurgos `nyc` is meant to essentially act as a replacement for the `node` bin, that gives you coverage for free -- I think I'd rather move the API bits into istanbul, and document their usage on that project.

Would love to have you [join the conversation here](https://github.com/istanbuljs/istanbuljs/issues/71) where were talking about where to document the API.

**Closed by bcoe** 2017-11-27 04:44 UTC
Labels: question
