### ISSUE TITLE
NYC Interfering with subprocess signal handling 

### ISSUE THREAD

**Issue by addisonj** [istanbuljs/nyc#470] opened 2016-12-13 06:24 UTC
## Expected Behavior
nyc should run tests the same as when the tests are run without NYC
## Observed Behavior
nyc, when running mocha unit tests, appears to be doing something with subprocesses spawned with `child_process.spawn`. Specifically, I have a unit under test that manages subprocesses. These subprocess can be killed. First the default `SIGTERM` is tried, but if the process does not exit, a `SIGKILL` is tried a second later. This test passes when run by mocha, but fails when run with nyc and mocha. A reduced test case follows:

## Bonus Points! Code (or Repository) that Reproduces Issue
A full gist with code and package.json at: https://gist.github.com/9d663a5fc7076777289c6b4bd3ef53b2

```JavaScript
const {spawn} = require('child_process')
const assert = require('assert')
describe('nyc doing weird stuff...', () => {
  it('should be able to force kill if it times out', (done) => {
    let s = `
    process.on('SIGTERM', function() { console.log('ignore!') })
    setInterval(function() {
      console.log('wtf')
    }, 40)
    `
    const args = ['-e', s.trim()]
    const scr = spawn('node', args)
    scr.stdout.setEncoding('utf8')
    scr.stderr.setEncoding('utf8')
    scr.stdout.on('data', (d) => {
      console.log(d)
    })
    scr.stderr.on('data', (d) => {
      console.log(d)
    })
    let gotStopped = false
    let forceKillTimeout
    function stop(cb) {
      scr.on('exit', (exitCode, signal) => {
        clearTimeout(forceKillTimeout)
        cb(null, 'script killed in response to signal : ' + signal)
      })
      forceKillTimeout = setTimeout(() => scr.kill('SIGKILL'), 1000)
      scr.kill()
    }
    setTimeout(() => {
      stop((err, status) => {
        if (err) return done(err)
        console.log(status)
        assert(status.indexOf('SIGKILL') > -1)
        done()
      })
    }, 150)
  })
})
```

With just mocha:
```Bash
$: mocha reducedTest.js
  nyc doing weird stuff...
wtf

ignore!

wtf

wtf
...

script killed in response to signal : SIGKILL
    ✓ should be able to force kill if it times out (1172ms)


  1 passing (1s)
```

With nyc
```Bash
$: nyc mocha reducedTest.js
  nyc doing weird stuff...
script killed in response to signal : SIGTERM
    1) should be able to force kill if it times out


  0 passing (176ms)
  1 failing

  1) nyc doing weird stuff... should be able to force kill if it times out:

      Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true

      at stop (reducedTest.js:6:1253)
      at ChildProcess.scr.on (reducedTest.js:6:702)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)



----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    81.48 |       50 |    66.67 |       88 |                |
 reducedTest.js |    81.48 |       50 |    66.67 |       88 |       16,19,36 |
----------------|----------|----------|----------|----------|----------------|
```

Note that no logs are seen from the subprocess in the nyc output even though we wait 150 mills before killing the process. 

## Forensic Information

Observed in **MacOs El Capitan**
Output text here: https://gist.github.com/2bbde16e2bcb80e567e6fb1a44f4948d

**Comment by addisonj** [comment] 2016-12-13 06:35
For kicks, I also run this in linux (under a docker image with node 6.90 and ubuntu 14.04) and had the same issue :(

**Comment by bcoe** [comment] 2016-12-13 07:00
@addisonj to be able to output coverage information prior to exiting, it's necessary for nyc to override signal-handling. The library https://github.com/tapjs/signal-exit is used to facilitate this.

Unfortunately, nyc would be unable to both collect coverage information from your spawned processes, and not override the signal handlers -- the project `signal-exit` attempts to be clever however, about maintaining a stack of listeners and firing them appropriately, If you wouldn't mind opening an issue on `signal-exit` maybe we can figure out a workaround for your tests.

**Comment by addisonj** [comment] 2016-12-13 07:08
So, interestingly, this works perfectly fine if instead of invoking the script with `node -e` the script is written to a file and then run, updated snippet:
```
const {spawn} = require('child_process')
const assert = require('assert')
const fs = require('fs')
describe('nyc doing weird stuff...', () => {
  it('should be able to force kill if it times out', (done) => {
    let s = `
    process.on('SIGTERM', function() { console.log('ignore!') })
    setInterval(function() {
      console.log('wtf')
    }, 40)
    `
    fs.writeFileSync('script.js', s)
    const args = ['script.js']
    const scr = spawn('node', args)
    scr.stdout.setEncoding('utf8')
    scr.stderr.setEncoding('utf8')
    scr.stdout.on('data', (d) => {
      console.log(d)
    })
    scr.stderr.on('data', (d) => {
      console.log(d)
    })
    let gotStopped = false
    let forceKillTimeout
    function stop(cb) {
      scr.on('exit', (exitCode, signal) => {
        clearTimeout(forceKillTimeout)
        cb(null, 'script killed in response to signal : ' + signal)
      })
      forceKillTimeout = setTimeout(() => scr.kill('SIGKILL'), 1000)
      scr.kill()
    }
    setTimeout(() => {
      stop((err, status) => {
        if (err) return done(err)
        console.log(status)
        assert(status.indexOf('SIGKILL') > -1)
        done()
      })
    }, 150)
  })
})
```

@bcoe this appears to have less to do with signal handling directly and more that with `node -e` the `spawn-wrap` doesn't seem to function as expected. Perhaps what node shim spawn-wrap is using does not properly handle the input, mainly, its not running the script to evaluate. That would explain no output from the subprocess as well as immediately dying to a `SIGTERM` where no handler was installed

@isaacs might be able to confirm if this is a possibility with `spawn-wrap`?

**Comment by bcoe** [comment] 2016-12-13 07:12
@addisonj was about to say, it sounds like we should probably carve out an exception in `spawn-wrap` for `-e` ... seems reasonable to avoid

**Comment by addisonj** [comment] 2016-12-13 07:18
👍  I have a workaround I can use for now, fun little diversion in the wonderful hacks to make test coverage work :) Thanks for the great tool!

**Comment by isaacs** [comment] 2016-12-13 18:15
This is kind of weird, because `-e` invocations are already explicitly passed through by spawn-wrap's shim.

Here's a test verifying that: https://gist.github.com/isaacs/9b05a4010304bdacd01fd8400fd74d94

Here's where it detects the `-e`: https://github.com/tapjs/spawn-wrap/blob/master/shim.js#L53

And here's where it says "no main, no wrap": https://github.com/tapjs/spawn-wrap/blob/master/shim.js#L88-L93

So... I'm not sure why the SIGTERM is not getting ignored.

**Comment by isaacs** [comment] 2016-12-13 18:17
Note that this test also passes when I run with `tap --cov test/exec-flag.js` or `nyc node test/exec-flag.js`

**Comment by bcoe** [comment] 2016-12-13 18:21
@addisonj @isaacs I'll keep this open until I have some time to look that's not just me poking through issues at 11PM -- sounds like a legitimate bug we should address, if we're already attempting to carve out an exception for `-e`.

**Comment by isaacs** [comment] 2016-12-13 18:35
A relevant difference in our scripts seems to be that mine is doing `process.execPath`, and yours is doing `'node'`.

The plot thickens!

**Comment by isaacs** [comment] 2016-12-13 18:56
I believe this comes down to a shortcoming in `foreground-child`.  The shim is doing its best to re-exec the child as its foreground process, but unless fg gets a bit smarter (and probably slower), it can't reliably know which ones are being caught and ignored by the child process.

What's actually happening is that the parent is killed with SIGTERM, parent (thinking the SIGTERM to be fatal) passes the `SIGTERM` to the child with its last breath, then kills itself with SIGTERM.  At this point, the child (not killed by the passed-along SIGTERM) keeps on trucking, which is itself rather odd, because I'd think that it _should_ get a fatal `SIGHUP` (since its parent process has exited).  But it doesn't appear to get a SIGHUP at all.

This works when passing a full path to `node`, because it doesn't have to do path resolution.  A possible solution would be for spawn-wrap's `index.js` file to not only not munge `'node' -e` calls, but in fact, fully resolve them to the next `node` executable in the PATH after the spawn-wrap shim.

**Comment by thetutlage** [comment] 2017-09-13 10:18
Since this issue is open, it also conflicts with puppeteer. Here's the issue I reported with them https://github.com/GoogleChrome/puppeteer/issues/763.

And the repo to reproduce the issue https://github.com/thetutlage/puppeteer-tests.

I tried digging into the codebase, and realized `foreground-child` is where things are getting messy.

**Comment by bcoe** [comment] 2017-09-16 20:05
@thetutlage If I had to guess, I'd bet the underlying issue is with the `spawn-wrap` module which is used to hook into exit signals (it might be worth creating an issue here as well).

Would love help digging into this further if you're so inclined 👍

**Comment by isaacs** [comment] 2017-09-18 16:23
The culprit is almost certainly foreground-child.

Because node does not have support for calling exec without a fork, the best we can do is run the new process with shared stdio, exit with the same status code and signal if the child process exits, and proxy any signals that come to the parent.

This approach has limitations.  Since `SIGKILL` and `SIGSTOP` cannot be caught, they can't be proxied either.  On windows, a few other signals also can't be caught and ignored, such as `SIGTERM`.

Without adding support for exec-without-fork, either in node core or via a binary addon, there's no other way to do the kinds of things that spawn-wrap (and thus, nyc) need to do in a consistent way.

**Comment by isaacs** [comment] 2017-09-18 16:25
Ah, in the issue referenced with GoogleChrome/puppeteer#763, it seems like the issue is just istanbul as such, since they are relying on consistent `toString()` output from functions.  If those functions are munged, their code will definitely change.  Maybe istanbul could transform functions such that `toString` was preserved?  I don't know.

**Comment by bcoe** [comment] 2017-09-18 17:11
@addisonj there have been quite a few changes to spawn-wrap since this issue was originally open, and it sounds like you've figured out work arounds. Mind if I close this out?

@thetutlage it sounds like there are issues specifically related to puppeteer  and should have its own issue. If I understand properly puppeteer injects code into a browser context, and is using the `toString()` on a function to perform magic? 

It feels like we'd probably need to coordinate a fix or workaround between the two projects.

**Comment by thetutlage** [comment] 2017-09-19 07:20
@bcoe Great that u guys are in favor of coordinating and getting a fix out. 

Also, I agree that they run the code in browser context and ideally it `nyc` may have nothing to do with that and same goes for `puppeteer` since they have a generic library to automate browser tasks.

But I am 100% sure that going forward, lots of testing engine implementations will be written in `puppeteer` and this issue will arise again.

I am happy to help in any way I can. Maybe creating appropriate issues with enough context, or digging into some code ( may need some guidance for that )

Thanks again 😄

**Closed** 2017-11-23 19:44 UTC
