### ISSUE TITLE
NYC output is empty

### ISSUE THREAD

**Issue by hayderma** [istanbuljs/nyc#822] opened 2018-04-26 20:20 UTC
I have been trying for hours to find the problem here, but I can't, I tried many things, this is my test file (`unit-test.js`) inside `projectRoot/test` 

```
var should = require('should');


var arr = [1, 2, 3];
function ap(ar) {
  a = ar;
  var L = a.length;
  if (L > 1) {
    a[L] = 4;
  }
  console.log(a);
  return a;
}

describe('#indexOf()', function () {
  it('should return -1 when the value is not present', function () {
    if (arr.length > 1) {
      should.equal(ap(arr)[3], 4);
      //should.equal(arr[2],3);
    }
  });
});
```

And this is my package.json:

```
{
  "name": "jsonave-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "eslint .",
   "test": " mocha test/unit-test.js --check-leaks --recursive --exit",
    "cover": "nyc npm test"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "http": "0.0.0",
    "jsonapter": "^2.0.3",
    "jsonave": "0.0.3",
    "moment": "^2.21.0",
    "nock": "^9.2.3",
    "should": "^13.2.1"
  },
  "devDependencies": {
    "eslint": "^4.19.1",
    "nyc": "^11.7.1"
  }
}
```
when i run , the output shows coverage all 0%  and no file name is mentioned, as shown below

```
$ npm run cover

> jsonave-test@1.0.0 cover C:\Users\h\WebstormProjects\jsonave-test
> nyc mocha



  #indexOf()
[ 1, 2, 3, 4 ]
    √ should return -1 when the value is not present


  1 passing (0ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

```

**Comment by JaKXz** [comment] 2018-05-01 02:32
This is because `nyc`'s instrumentation /reporting works based the files you `require` (or `import`) in your tests. If you split `unit-test.js` into two files, one with the test and the other with the test subject, it should list the test subject file in the output. :)

**Comment by redonkulus** [comment] 2018-05-03 21:43
@JaKXz I'm getting the same issue, here is the stub code (after trying to add a `stub.js` file as you mentioned above):

```js
// test.js
const assert = require('assert');
const stub = require('./stub');
it('should have tests', () => assert.equal(stub, true));
```

```js
// stub.js
module.exports = true;
```

```

**Comment by JaKXz** [comment] 2018-05-04 08:46
Why are you setting `instrunent: false`?

**Comment by redonkulus** [comment] 2018-05-04 16:47
@JaKXz My project which uses babel had that set already. Even in this simple test, turning it to `true` doesn't collect coverage. I've uploaded the files to a repo so you can try it out if you want.

https://github.com/redonkulus/nyctest

**Comment by JaKXz** [comment] 2018-05-04 16:50
Interesting. Try this tutorial: https://istanbul.js.org/docs/tutorials/es2015/

Coverage with babel should be no problem.

**Comment by JaKXz** [comment] 2018-05-04 16:52
I'm really confused by this because all I did to get your example repo working was remove `.nycrc`

**Comment by redonkulus** [comment] 2018-05-04 17:48
> I'm really confused by this because all I did to get your example repo working was remove .nycrc

So is that a bug in how nyc is processing the config file?

**Comment by redonkulus** [comment] 2018-05-16 17:11
@JaKXz ping

**Comment by JaKXz** [comment] 2018-05-16 17:15
I think this issue should be re-phrased as a bug, but the bug is probably in yargs not NYC. 

Please close this issue and open one there. 

For now I hope you have an adequate workaround.

**Comment by sibajeeray** [comment] 2018-07-04 10:20
The problem is, Mocha is not exiting after its execution. So coverage report is unable to print as the execution is hold by mocha.
In Script of package.json mention --exit after mocha.
EX- nyc --reporter=html --reporter=text mocha --exit

**Comment by hayderma** [comment] 2018-07-04 22:48
I have not worked on NYC since opening this issue, for those who still have their projects running, if @sibajeeray answer solves the issue, feel free to close it, else I will try something on it in the next couple of days.

**Comment by 75lb** [comment] 2019-01-02 13:06
I have the same issue, reproduced using node v6.14.4 and v11.4.0.

In an empty directory, install the deps.

```
$ npm i mocha nyc
$ npm ls --depth 0
broken-nyc@1.0.0 /Users/llobrook/Documents/tmp/broken-nyc
├── mocha@5.2.0
└── nyc@13.1.0
```

Create this file `test.js`:

```js
it('one', function () {
  return 'one'
})

it('two', function () {
  return 'two'
})
```

Run mocha with nyc. 

```
$ npx nyc mocha test.js


  ✓ one
  ✓ two

  2 passing (8ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

As you can see, the report is empty. Any ideas?

**Comment by quentinvernot** [comment] 2019-01-02 14:56
@75lb I added a second file to your repro, I get coverage when I do that:

lib.js:
```js
module.exports = { inc: x => x + 1 };
```

test.js:
```js
const { inc } = require('./lib');
it('1', () => inc('1'))
```

```
$ npx nyc mocha test.js


  ✓ 1

  1 passing (6ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 lib.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Maybe nyc doesn't provide coverage inside the test files by default?

**Comment by FraBle** [comment] 2019-02-06 00:32
I currently experience the same issue as reported by @AnanyaJha

**Comment by Antonius-S** [comment] 2019-02-06 11:23
The same issue. Reproduced with stub.js from [this post](https://github.com/istanbuljs/nyc/issues/822#issuecomment-386446711) and nyc installed globally. In my case issue seems to happen only with global mocha:
```
D:\Projects\nyc-test>nyc node_modules\.bin\mocha


  √ should have tests

  1 passing (39ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 stub.js  |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|

D:\Projects\nyc-test>nyc mocha


  √ should have tests

  1 passing (39ms)

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

**Comment by AnanyaJha** [comment] 2019-02-27 23:01
@Antonius-S were you able to get your setup working?

**Comment by Antonius-S** [comment] 2019-03-12 15:49
Found one more workaround that doesn't use softlinks. Solution is for Windows and globally installed mocha, path to Node must be in `PATH` and mocha must be in `%Node%\node_modules\mocha`. Of course you can change prerequisites by changing the script.

Copy the text below and save as `%yourproject%\node_modules\.bin\mocha.cmd`

```bat
:: This batch launches globally installed mocha entry point

@ECHO OFF
SETLOCAL

SET NodeDir=
FOR /F %%S IN ('where node.exe') DO SET NodeDir=%%~dpS
IF NOT DEFINED NodeDir ECHO Node.exe not found in path && PAUSE && GOTO :EOF

node  "%NodeDir%\node_modules\mocha\bin\mocha" %*
```

**Comment by bcoe** [comment] 2019-03-12 17:38
there are a variety of reasons why coverage might be blank, and this thread seems to not be related to one specific cause. I'm closing this issue, but folks should feel free to open issues more specific to the problems they're bumping into; ideally with a minimal reproduction in a repo.

**Closed by bcoe** 2019-03-12 17:38 UTC
Labels: question

**Comment by Antonius-S** [comment] 2019-03-13 07:15
@bcoe what do you think about my case (no coverage with global mocha but local mocha works OK)? Is it NYC issue or mocha's? Should I report it separately?

**Comment by bcoe** [comment] 2019-03-13 17:21
@Antonius-S feel free to open an issue :+1: just want to make sure we're very specific about how to reproduce; these catch all issues almost never get solved, because there are multiple causes of empty coverage.

**Comment by winnieBear** [comment] 2019-04-11 09:33
> We should add to the troubleshooting steps to add `cache: false` somewhere in your nyc config when trying to reproduce. cc @bcoe [where do you think is best, the Issue template?]
> 
> Is everyone in this thread satisfied enough to close this issue? Perhaps a PR for ? :)

maybe you can add 'cache-dir=your_cache_dir', so you can fix and get result quickly.

**Comment by arjunpanicker** [comment] 2019-04-24 11:00
> The problem is, Mocha is not exiting after its execution. So coverage report is unable to print as the execution is hold by mocha.
> In Script of package.json mention --exit after mocha.
> EX- nyc --reporter=html --reporter=text mocha --exit

Thank you. This worked like a charm.

**Comment by diiiego83** [comment] 2019-05-09 10:16
Hi had the same issue. mocha works correctly but nyc output and empty report.

```
"scripts": {
    "test": "mocha ./dist/utest/test.js --exit",
    "coverage": "nyc npm test",
  },  
  "nyc": {
    "include": [
      "dist/**/*.js"
    ],
    "reporter": [
      "text-summary",
      "html",
      "cobertura"
    ],
    "sourceMap": true,
    "instrument": true
}
```

```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```

**Comment by coreyfarrell** [comment] 2019-05-09 11:44
@diiiego83 Having the same symptom does not mean you have the same issue (cause).  Please post a new issue including all required information so we can troubleshoot your issue.

**Comment by davegildea** [comment] 2020-04-06 08:24
I had this issue running in cmd however when I changed to using Ubuntu on WSL it worked a treat. So the process not exiting correctly appears to cause the issue with nyc not getting the reports

**Comment by ZaidRehman** [comment] 2021-03-11 09:02
Still facing this issue. I have tried all the above mentioned solution.

**Comment by zhuqingguang** [comment] 2021-07-06 09:30
> Still facing this issue. I have tried all the above-mentioned solution.

I have found if i test compiled code in `dist` and typescript has generate sourceMap, i must include both `dist` and `src`.
Have a try.

**Comment by sayo96** [comment] 2023-04-25 08:29
The --exit option did not work for me. Is there any alternate fixes for this

In my case the tests are within the src folder and i'm running nyc command like:
`nyc  mocha --recursive ./src`.

The tests are passing but the coverage report is empty!
<img width="777" alt="Screenshot 2023-04-25 at 1 59 35 pm" src="https://user-images.githubusercontent.com/26695583/234219776-05417ba4-c0b6-4619-892a-8957d5342a1b.png">

**Comment by alecgibson** [comment] 2024-02-08 10:24
In case this helps any future travellers: our coverage broke when I declared a variable `var arguments = []`.

`arguments` isn't a reserved word (which is why tests correctly pass), but does have [special meaning](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#identifiers_with_special_meanings), and maybe this was tripping up `nyc`. Would have been nice to have had some warning about this.

**Comment by tharindug99** [comment] 2024-11-02 05:39
```
> mocha@1.0.0 test
> nyc --all mocha "test/*.spec.js"

Initiating Functions


  Basic Calculations
    ✔ should add 1 and 2 to get 3
    ✔ should add 5 and 5 to get 10
    ✔ should subtract 5 from 10 to get 5
    ✔ should subtract 8 from 20 to get 12
    ✔ should multiply 2 and 3 to get 6
    ✔ should multiply 4 and 5 to get 20
    ✔ should divide 10 by 2 to get 5
    ✔ should divide 20 by 4 to get 5


  8 passing (7ms)

------------|---------|----------|---------|---------|-------------------
File        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
------------|---------|----------|---------|---------|-------------------
All files   |       0 |        0 |       0 |       0 | 
 myClass.js |       0 |        0 |       0 |       0 | 3-30
------------|---------|----------|---------|---------|-------------------
```



Output is shown as empty.

```
{
  "name": "mocha",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "nyc --all mocha \"test/*.spec.js\" "
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "devDependencies": {
    "mocha": "^10.7.3",
    "nyc": "^17.1.0"
  },
  "type": "module",
  "dependencies": {
    "chai": "^5.1.2",
    "source-map-support": "^0.5.21"
  },
  "nyc": {
    "include": [
      "src/**/*.js"
    ],
    "exclude": [
      "Data/*.js"
    ]
  }
}
```

Please help to fix this
