### ISSUE TITLE
Question: __coverage__ is reset when navigating thru url

### ISSUE THREAD

**Issue by Hystle** [istanbuljs/nyc#1117] opened 2019-05-13 18:10 UTC
I am trying to get code coverage by consuming the __coverage__ object after a series of automation tests run. Here is how I do it:
 
1. Instrument code with nyc (v13.3.0) and node (8.11.3)
2. Put the instrumented code on a nginx server
3. Run e2e protractor test on it
4. After all test specs completed, I use Protractor's onComplete() to grab the __coverage__ object from the browser
5. Use nyc reporter to generate the report
 
However I noticed that the every time when the automation does **URL navigation** (i.e. typing the url directly on the browser which I think triggers a server request to fetch the page) rather than navigate via the app buttons, it **causes the __coverage__ object in the browser to reset**. This leads us to not being able to get a total coverage of all test suites combined.
 
I am wondering if this is expected from nyc? If it is, is there any workaround?

**Comment by AndrewFinlay** [comment] 2019-05-13 23:18
Hi @Hystle, from the sound of it I run a pretty similar setup for my client side e2e tests.  I'm testing old AngularJS pages using Protractor to drive Chrome.  To capture the coverage objects I'm using a plugin called [protractor-istanbul-plugin](https://github.com/bennyhat/protractor-istanbul-plugin).  It's old and abandoned but it works for what we're doing, and gives us coverage object files that we can use to generate the report.  

From the source for [Protractor plugins](https://github.com/angular/protractor/blob/master/lib/plugins.ts), there is a `postTest` hook that you can use to access the `__coverage__` object.   Though I'm not completely certain on this, I can't see a straightforward way of doing this from a Protractor config file.

**Comment by coreyfarrell** [comment] 2019-05-14 10:18
nyc does not run in the browser, but yes this is expected.  instrumented code uses the global variable `__coverage__` to store coverage counters.  So in the browser this is effectively `window.__coverage__`.  When the browser navigates to a new page you get a new global state (the browser does this, not nyc or istanbul).  The only exception would be when single page app intercepts the navigation and performs an 'internal' navigation (using history API for example).

istanbul-lib-instrument has options to control how the `__coverage__` variable is stored but this has not been exposed elsewhere.  In theory if these options were exposed it could be setup so to use `window.top` as the global variable, then you would setup the browser to open a page that contained an `<iframe>`, and run the actual tests inside that iframe.  Obviously I haven't done real-life tests of this functionality, you would still need to make sure that all navigation occurs against the iframe and not against `window.top`.  This feature will not be exposed via nyc, this is something that would be appropriate for `babel-plugin-istanbul` to support.

**Comment by Hystle** [comment] 2019-05-14 21:39
Thanks both @AndrewFinlay @coreyfarrell for the detailed reply. 
As workaround, I'll probably try pulling the __coverage__ object before each url navigation happens individually, and store in the .nyc_output dir. Eventually the report will consume the merged one at the end of the full automation run..

**Comment by coreyfarrell** [comment] 2019-05-17 19:23
I'm closing this as it is not a bug in nyc.  I've opened https://github.com/istanbuljs/babel-plugin-istanbul/issues/208 as the only possible action that could be taken is to add support for babel-plugin-istanbul to use `window.top` as the global variable.

**Closed by coreyfarrell** 2019-05-17 19:23 UTC

**Comment by evilaliv3** [comment] 2019-09-14 09:54
@Hystle @coreyfarrell: have you found a solution for this?

**Comment by evilaliv3** [comment] 2019-09-14 13:24
@Hystle @coreyfarrell : actually in [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) we managed to handle this using an ```inline``` plugin defining postTest and using the onComplete callback: https://github.com/globaleaks/GlobaLeaks/blob/master/client/tests/protractor-coverage.config.js

**Comment by arcanum0** [comment] 2020-06-12 08:39
Hi @evilaliv3 I used a similar approach to such as yours 
Although I'm facing an error 

> E/launcher - BUG: launcher exited with 1 tasks remaining

There is not error if I just use the onComplete like this but again __coverage__ resets itself
> configuration.onComplete=()=>{  
    browser.driver.executeScript("return __coverage__;").then(function(val) {  
    filesystem.writeFileSync("./coverage/coverage.json", JSON.stringify(val));  
   });  
}

Sorry for being vague but I can't seem to figure out where I'm going wrong since I've imported and installed the right modules.
