### ISSUE TITLE
No coverage with mocha

### ISSUE THREAD

**Issue by ilsundal** [istanbuljs/nyc#1319] opened 2020-05-20 08:05 UTC
I don't get any code coverage statistics with istanbul (nyc) and mocha.

I have installed istanbul (nyc) as follows:

`$ npm install --save-dev nyc`

And then I have modified my package.json "scripts" to this:

```
"scripts": {
  "test": "nyc mocha test/descriptor-util-test.js"
}
```

Yet, when I run this command:

`$ npm test`

then I get this result:

```
<SNIP>
sensitive property
  ✓ should succeed with sensitive string
  ✓ should succeed with insensitive string
  ✓ should succeed with sensitive array
  ✓ should succeed with insensitive array
  ✓ should succeed with sensitive object (all properties)
  ✓ should succeed with object with sensitive and insensitive properties
  ✓ should succeed with map-inline object with sensitive and insensitive properties
  ✓ should succeed with map-reference object with sensitive and insensitive properties
method example
  ✓ should succeed with a valid descriptor

85 passing (62ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```
So, no code coverage stats :(

Any ideas on what is wrong? Thanks!

**Comment by coreyfarrell** [comment] 2020-05-20 11:40
Many people are using nyc and mocha together without issue, you have something in your setup which is preventing it from working.  Without linking to a reproduction repository demonstrating the issue nobody will be able to help you.

**Comment by ilsundal** [comment] 2020-05-20 12:00
Yeah, but I was hoping there was a verbose mode or log or similar that could quickly help me pinpoint the issue or at least point me in the right direction to resolve the issue. I have a pretty standard Mocha-based test setup, so I am at a loss as to why this doesn't work out of the box.

**Comment by robertdumitrescu** [comment] 2020-05-24 14:46
Let me guess... you are using the ESM modules in Node.js. I had the same issues and switched to C8 for now till it gets implemented. NYC currently doesn't support ESM modules.

**Comment by PavelTselyuk** [comment] 2020-05-26 00:14
Maybe it's not your case, but i had the same issue. I didn't use 'use strict' mode and named one of my variables "static" which is strict mode reserved word, after I renamed this vaiable and it was fixed

**Comment by coreyfarrell** [comment] 2020-05-26 11:11
@ilsundal you can try setting environment `NODE_DEBUG=nyc`.  Since you have not provided the required information I'm closing this issue, if you post a link to a repository demonstrating an issue we can reopen.

**Closed by coreyfarrell** 2020-05-26 11:11 UTC
Labels: needs more information
