### ISSUE TITLE
Yargs related error on nyc using it with mocha

### ISSUE THREAD

**Issue by anonrig** [istanbuljs/nyc#712] opened 2017-11-06 22:19 UTC
Hello,

I'm receiving this error on CircleCI with NodeJs 8.8.0, but on local machine working it with 8.6.0 I don't receive this error. I don't think that it's related to node version but let me point it out :)

```bash
> faida-core@0.1.0 test /home/circleci/repo
> CONFIG=config/test.json ./node_modules/.bin/nyc --reporter=html --reporter=text --all ./node_modules/.bin/mocha --require ./test/index.js "test/**/*.js"

YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/circleci/repo/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/circleci/repo/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/circleci/repo/node_modules/nyc/bin/nyc.js:20:54)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at /home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (<anonymous>)
    at module.exports (/home/circleci/repo/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version (/home/circleci/repo/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs (/home/circleci/repo/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> (/home/circleci/repo/node_modules/nyc/bin/nyc.js:66:16)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
info: Reading config file config/test.json
```

**Comment by AdamVig** [comment] 2017-11-08 14:37
I got the same error on my local machine (macOS High Sierra 10.13.1) with `npm run test`. My test script is `PORT=7863 nyc ava`.

**Comment by bcoe** [comment] 2017-11-08 16:28
@anonrig @AdamVig could you share a link to a project (or a minimal reproduction) that is having this issue? From reading that stack trace, it looks like the issue is related to the parsing of a field in `test.json`.

**Comment by anonrig** [comment] 2017-11-08 20:09
I can not reproduce this error on my local machine, but if it's helpful here is the `.circleci/config.yml`

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.8.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint
      - run: npm test

      - store_artifacts:
          path: coverage

```

**Comment by AdamVig** [comment] 2017-11-08 20:14
My project: [stockpile-co/api](https://github.com/stockpile-co/api).

The full error from my machine:
```
YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at [path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (native)
    at module.exports ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs ([path redacted]/stockpile/api/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> ([path redacted]/stockpile/api/node_modules/nyc/bin/nyc.js:20:54)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
YError: Invalid first argument. Expected string or function but received boolean.
    at argumentTypeError ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:70:9)
    at [path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:52:39
    at Array.forEach (native)
    at module.exports ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/lib/argsert.js:45:21)
    at Object.Yargs.self.version ([path redacted]/stockpile/api/node_modules/nyc/node_modules/yargs/yargs.js:715:5)
    at Object.Config.buildYargs ([path redacted]/stockpile/api/node_modules/nyc/lib/config-util.js:213:6)
    at Object.<anonymous> ([path redacted]/stockpile/api/node_modules/nyc/bin/nyc.js:66:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by bcoe** [comment] 2017-11-08 20:18
very interesting to me that it's only happening on the Circle CI machine, I think there's a chance that it's two versions of yargs competing with each other. On your local machine, try deleting your entire `node_modules` folder and re-installing; I would also ensure you're on the same version of npm as CircleCI -- maybe we can figure out the exact issue.

**Comment by anonrig** [comment] 2017-11-08 20:24
@bcoe Unfortunately, CircleCI doesn't offer 8.9.1 in their built-in docker image.

`Error response from daemon: manifest for circleci/node:8.9.1 not found`

On the other hand, I think you're a genius. I did `npm ls` and saw these versions of yargs:

yargs-parser@8.0.0
yargs@10.0.3
yargs@3.10.0 - Used by nyc@11.3.0
yargs@3.32.0 - Used by nconf

(Couldn't trace any others, my eyes bleed.) But here's the GIST: https://gist.github.com/anonrig/3759e8f643374fb1fcaa1e18c74c96bf

**Comment by AdamVig** [comment] 2017-11-08 20:24
All set! `rm -rf node_modules && npm i` fixes the error for me. Good intuition, @bcoe.

@anonrig to do the above on CircleCI, you may want to look into [Clearing the Cache](https://circleci.com/docs/1.0/how-cache-works/#clearing-cache).

**Comment by anonrig** [comment] 2017-11-08 20:27
Thanks @AdamVig that fixed my error.

It's seems that there are lots of mysteries in this world. Including yargs.

**Comment by bcoe** [comment] 2017-11-08 21:59
Great; I think the underlying issue is that the wrong thing sometimes gets hoisted to the top-level folder by npm when a dependency is upgraded.

It might be worth opening an issue on npm/npm regarding this, I'm going to close this issue on nyc since I think we've gotten to the bottom of things 👍

**Closed by bcoe** 2017-11-08 21:59 UTC
Labels: triaged
