### ISSUE TITLE
nyc 15 gives no coverage without the useSpawnWrap option

### ISSUE THREAD

**Issue by adjerbetian** [istanbuljs/nyc#1303] opened 2020-04-13 14:58 UTC
##  Link to bug demonstration repository

https://github.com/adjerbetian/nyc-bug-demo-use-spawn

## Expected Behavior

I would want to have the coverage, but I get nothing in the output

![image](https://user-images.githubusercontent.com/5993086/79130246-ee0b9100-7da6-11ea-8d37-25cb52b825b6.png)

I tried to debug, and when I use the flag `--use-spawn-wrap` I get the expected result:

![image](https://user-images.githubusercontent.com/5993086/79130351-1c896c00-7da7-11ea-8e9d-6fa6cc6d52fa.png)

:memo: This problem does not occur on `nyc@14`.

### Troubleshooting steps
- run `npx nyc mocha` --> ❌ no coverage 
- run `npx nyc --use-spawn-wrap mocha` --> :heavy_check_mark: coverage
- [x] still occurring when I put `cache: false` in my nyc config

## Environment Information
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 10.25 GB / 31.07 GB
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  npmPackages:
    nyc: ^15.0.1 => 15.0.1 
```

**Comment by coreyfarrell** [comment] 2020-04-14 12:28
I am not able to reproduce this issue, `npx nyc mocha` in your repository works correctly on Fedora 30 and Ubuntu 18.04.4.

Fedora 30 is what I run locally, I tested with node 12.16.2 installed by nvm.  I tested ubuntu under docker using the `ubuntu:18.04` image and again installing node.js using nvm.

This is an important issue for us to figure out as `--use-spawn-wrap` is an option that was added "just in case", the intent is to eventually remove it from a future semver-major.

Your environment info lists node 12.16.1 as being installed to `/usr/bin/node`.  How did you install this?  `apt-get install nodejs` gave me 8.10.0 and `nvm` doesn't install to `/usr/bin`.

**Comment by adjerbetian** [comment] 2020-04-15 18:07
@coreyfarrell Thank you for answering.

My ubuntu just updated the node version to `12.16.2` and the problem is gone. I tried to look at the [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.16.2) to see what it could be but it's too big.

I suppose we can close here, unless you want to keep digging.

**Comment by coreyfarrell** [comment] 2020-04-15 18:16
Thanks for the update.  This is odd as I'm not seeing the issue using 12.16.1 on Fedora either.  Without being able to reproduce I think we can close this issue, if you do ever see it again please be sure to post a new issue!

**Closed by coreyfarrell** 2020-04-15 18:16 UTC
Labels: needs-investigation, waiting-on-feedback

**Comment by danielSONCCO** [comment] 2020-04-21 10:37
@coreyfarrell do you reproduce if you employ ?
- node 12.13.0
- nyc 15.0.1

bug looks coming of the usage of `node-preload` https://github.com/istanbuljs/nyc/blob/master/bin/nyc.js#L62
https://github.com/cfware/node-preload#limitations
Those limitations can explain that the result isn't deterministic

On my pc, without the `useSpawnWrap` option, `lib/wrap.js` is not executed by that preload
This causes that `onExit` isn't called, then `writeCoverageFile` isn't called

wdyt of replacing `node-preload` by something else ?

**Comment by coreyfarrell** [comment] 2020-04-21 11:03
Worker threads are not supported by spawn-wrap at all.  node-preload is the replacement, if it is failing in a case where spawn-wrap worked I need to see a reproducible demo suit can be fixed.  Be aware spawn-wrap fails in many situations,  especially on Windows.

**Comment by leolcao** [comment] 2020-05-02 14:48
@coreyfarrell I can reproduce this issue by using the @adjerbetian's git repo: https://github.com/adjerbetian/nyc-bug-demo-use-spawn

My desktop is Windows 10 10.0.19041.208, and the node.js environment is:
- node.js: 12.16.2, installed by nvs
- npm: 6.14.4

The reproduce steps:
- clone https://github.com/adjerbetian/nyc-bug-demo-use-spawn in git bash
- run `pnpm install  --shamefully-hoist`
- run `npm run nyc:wrong`, and get this:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'node-preload.js'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1296:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:68:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-ts@1.0.0 nyc:wrong: `nyc mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-ts@1.0.0 nyc:wrong script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
- run `npm run nyc:correct` will ok to get good result:
```
> nyc --use-spawn-wrap mocha



  plus
    √ should add 2 numbers


  1 passing (11ms)

--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------|---------|----------|---------|---------|-------------------
All files     |     100 |      100 |     100 |     100 |
 plus.js      |     100 |      100 |     100 |     100 |
 plus.spec.js |     100 |      100 |     100 |     100 |
--------------|---------|----------|---------|---------|-------------------
```
