### ISSUE TITLE
index.js of modules required in test files are reported

### ISSUE THREAD

**Issue by ngryman** [istanbuljs/nyc#395] opened 2016-09-16 00:01 UTC
Hi guys,

I'm struggling with this. It may be a `nyc` bug under certain conditions.

I'm using [lerna](https://github.com/lerna/lerna) to manage multiple packages that may depend on each others. Lerna manages this by creating a `package.json` and a `index.js` in the `node_modules` of dependant packages. It does not create symlinks.

In some tests I reference another local package. The file gets reported. It shouldn't.
I've tried playing with `include` and `exclude` directive without success 😢 
## Observed Behavior

All local packages required in a test file gets reported.

**Output**

![image](https://cloud.githubusercontent.com/assets/892048/18571067/567442c4-7ba7-11e6-8817-17a6297a2086.png)

**Test file causing the issue**
![image](https://cloud.githubusercontent.com/assets/892048/18571180/5a2b4696-7ba8-11e6-8c51-1bc21427a058.png)
## Expected Behavior

No `index.js` files should be reported.
## Bonus Points! Code (or Repository) that Reproduces Issue

**Master package.json (stripped)** [Full version](https://gist.github.com/ngryman/476365399d5f3c162f995199df52ef92#file-package-json)

``` json
{
  "scripts": {
    "test": "nyc ava packages/*/test"
  },
  "ava": {
    "require": [
      "babel-register"
    ]
  },
  "babel": {
    "plugins": [
      "transform-es2015-parameters"
    ],
    "env": {
      "development": {
        "plugins": [
          "istanbul"
        ],
        "sourceMaps": "inline"
      }
    }
  },
  "nyc": {
    "include": [
      "packages/*/lib/*.js"
    ],
    "sourceMap": false,
    "instrument": false
  }
}
```
## Forensic Information

**Operating System:**
`Darwin macbook-ngryman 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64`

**Environment Information:** 
https://gist.github.com/ngryman/476365399d5f3c162f995199df52ef92

**Comment by bcoe** [comment] 2017-01-20 01:00
@ngryman are you still running into these issues, it seems as though these days lerna does create a symlink unless I'm mistaken?

**Comment by ngryman** [comment] 2017-01-21 13:54
I ended up dropping lerna so I don't know if it's now resolved with a newer version.

**Comment by bcoe** [comment] 2017-01-23 06:22
@ngryman 👍 alright if I close this out for the time being then? my own tests with lerna so far have been pretty promising.

**Comment by ngryman** [comment] 2017-01-23 11:59
I tested again with my old branch. I updated to `lerna-2.0.0-beta.32`.
I ended up with this output:

<details>
```bash
---------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
File                                                                                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
 ./helpers/Users/ngryman/Projects/arbre/helpers/                                       |      100 |      100 |      100 |      100 |                |
  tree.js                                                                              |      100 |      100 |      100 |      100 |                |
 ./packages/arbre-convert/Users/ngryman/Projects/arbre/packages/arbre-convert/         |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 ./packages/arbre-convert/lib/Users/ngryman/Projects/arbre/packages/arbre-convert/lib/ |      100 |      100 |      100 |      100 |                |
  from-array.js                                                                        |      100 |      100 |      100 |      100 |                |
  from-json.js                                                                         |      100 |      100 |      100 |      100 |                |
  from-object.js                                                                       |      100 |      100 |      100 |      100 |                |
  to-array.js                                                                          |      100 |      100 |      100 |      100 |                |
  to-json.js                                                                           |      100 |      100 |      100 |      100 |                |
  to-object.js                                                                         |      100 |      100 |      100 |      100 |                |
 ./packages/arbre-manipulate/Users/ngryman/Projects/arbre/packages/arbre-manipulate/   |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 ./packages/arbre-query/Users/ngryman/Projects/arbre/packages/arbre-query/             |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 ./packages/arbre-traverse/Users/ngryman/Projects/arbre/packages/arbre-traverse/       |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 ./packages/arbre/Users/ngryman/Projects/arbre/packages/arbre/                         |       85 |      100 |       50 |    93.33 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
  node.js                                                                              |       85 |      100 |       50 |    93.33 |             13 |
 Users/ngryman/Projects/arbre/helpers/                                                 |      100 |      100 |      100 |      100 |                |
  tree.js                                                                              |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre-convert/                                  |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre-convert/lib/                              |      100 |      100 |      100 |      100 |                |
  from-array.js                                                                        |      100 |      100 |      100 |      100 |                |
  from-json.js                                                                         |      100 |      100 |      100 |      100 |                |
  from-object.js                                                                       |      100 |      100 |      100 |      100 |                |
  to-array.js                                                                          |      100 |      100 |      100 |      100 |                |
  to-json.js                                                                           |      100 |      100 |      100 |      100 |                |
  to-object.js                                                                         |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre-manipulate/                               |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre-query/                                    |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre-traverse/                                 |      100 |      100 |      100 |      100 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
 Users/ngryman/Projects/arbre/packages/arbre/                                          |    90.91 |      100 |       50 |    90.91 |                |
  index.js                                                                             |      100 |      100 |      100 |      100 |                |
  node.js                                                                              |    90.91 |      100 |       50 |    90.91 |             13 |
---------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
All files                                                                              |    99.38 |      100 |    97.92 |    99.44 |                |
---------------------------------------------------------------------------------------|----------|----------|----------|----------|----------------|
```
</details>
<br>

I'm testing all at once using my root `package.json`: `nyc ava packages/*/test`. Are you doing the same in your project using `lerna`?

**Comment by cif** [comment] 2017-02-03 19:48
I had this same issue. For correct reporting (and better tests! 😉) you have to make absolutely sure any files which import dependencies from your external Lerna modules are being smashed with [proxyquire](https://github.com/thlorenz/proxyquire) (use `noCallThru()` and `proxyquireStrict()`). In my case, I had a test which imported a project file which imported another project file which imported the Lerna module showing up in the report as uncovered since the tests are within that package/module.  The test's import was not proxyquired and caused nyc to follow the require cache object chain down into the external module and into two more modules.

Hope that helps someone else!

**Comment by bcoe** [comment] 2017-02-06 21:19
@cif @ngryman do you think it would be worth documenting this with a tutorial here?

https://github.com/istanbuljs/istanbuljs.github.io

If so, would greatly appreciate someone opening an issue 👍

**Comment by ngryman** [comment] 2017-02-07 13:59
@bcoe Yes it would be great. I have to admit that I did not totally understood @cif's solution. It would be nice if it was explained in detail in some sort of *recipe* or `nyc` + `lerna`. 👍

**Comment by cif** [comment] 2017-02-07 16:44
@ngryman @bcoe a quick example of how proxyquire works: 

a.js 
 `export const a = () => 'a result';`

b.js
``` 
import { a } from './a.js';
export default const b = () => {
 if (typeof a() === 'string') {
    return false;
 } 
 return true;
}
```

b.test.js
```
import { stub } from 'sinon';
import { noCallThru } from 'proxyquire';
// noCallThru prevents *any* import in b.js from using the actual dep
const proxyquireStrict = noCallThru();  
const mockA = stub();
const b = proxyquireStrict(
  './b.js', 
  {
    './a.js': { a: mockA }
  }
).default;  // <-- note proxyquire returns module.exports

mockA.returns('some string');
it.is(b(), false);

// now, test other code path
mockA.returns(false);
is.is(b(), true);

```
The basic function is to 'hijack' the require / import statements in any dependencies and replace them with mocks. This ensures you are testing logic in your target file, not its dependencies.  

**That said...** As our team continues to move our "monolithic" module to Lerna, there are modules such as `project-constants` which are heavily imported in many project files and are getting picked up by the lcov reports.  While you could proxyquire every test, for larger projects it is not always practical.

The only difference with Lerna is that Lerna uses symlinks in node_modules so you don't have to republish changes to npm when developing interdependent modules locally. Not sure if that gives you any hints @bcoe ? 

Before I do a Lerna + NYC tutorial I want to do some research into ways to prevent reporter from following the symlinks. I will probably start by looking at what require.cache looks like after running some small test batches. I'm not familiar with NYC/istanbul codebases but any pointers will be helpful, happy to put up a PR should I find a clean solution

**Comment by cif** [comment] 2017-02-20 20:59
Coming back with an update on this one (and tail between my legs). While proxyquire is great for unit tests in general... Turns out this case of nyc "bad" module reporting was just an issue with `babel-plugin-istanbul` being ran when building modules (DOH!).  This wasn't caused by lerna, nor by nyc. 
Coverage data was being slapped right in my dist/index files. Had I simply checked there would have been obvious more quickly.  I'd be willing to bet @ngryman was having the same issue, would be interested in knowing if that was it.

**Comment by bcoe** [comment] 2017-02-21 00:26
@cif so, sounds like we're working pretty well with lerna setups this point (which is good, since I'm about to start moving some of our modules over to lerna!).

**Comment by cif** [comment] 2017-02-21 18:13
Yes, this was definitely that plugin however I am still having some trouble getting both individual modules to test and the outer most project to work. Seems related to https://github.com/istanbuljs/nyc/issues/294

Outer project nyc errors:
```
TypeError: Cannot read property '0' of undefined
      at _interopRequireDefault (builder-services/src/productService.js:1:8638
```
Which looks like babel is mangling up the file before the test. Mocha runs all tests fine. nyc block in package.json:
```
"nyc": {
    "lines": 90,
    "statements": 90,
    "functions": 80,
    "branches": 80,
    "include": [
      "**/src/**/*.js"
    ],
    "exclude": [
      "**/src/**/*.test.js",
      "**/src/public",
      "**/src/harness",
      "**/src/vendor",
      "**/src/test",
      "**/src/automation",
      "**/dist"
    ],
    "reporter": [
      "lcov",
      "text-summary",
      "json-summary"
    ],
    "cache": true,
    "all": true,
    "check-coverage": true,
    "report-dir": "coverage/nyc",
    "sourceMap": false,
    "instrument": false
  },
```

**Comment by cif** [comment] 2017-02-21 18:38
Interesting. Change down from `10.1.2-candidate.0` back to `10.0.0` solved the issue. Not sure what's in the works for 10.1, but the files that were causing failures contained runtime polyfill promises in one case, and JSX/render in the other. Seems like something new is causing istanbul plugin and transpiling out of sequence with other plugins/presets?

**Comment by bcoe** [comment] 2017-02-21 19:17
@cif are you able to share a project that can reproduce this behavior? I believe the issues in #294 should no longer be happening.

**Comment by cif** [comment] 2017-02-21 19:21
Unfortunately the repo I'm working with is owned by a progressive, yet extra large shoe corporation 🙃

**Comment by bcoe** [comment] 2017-02-21 19:24
@cif if it was related to #294, perhaps try:

`npm i nyc@latest --save-dev`
`rm -rf ./node_modules/.cache`

If this doesn't work, you could also try disabling the cache entirely, like so:

`nyc --cache=false`

**Comment by cif** [comment] 2017-02-21 19:27
Clearing .cache fixed it right up. 👍

**Comment by bcoe** [comment] 2017-02-21 19:32
@cif weird! we use `CACHE_VERSION` to try to bust the cache; not sure what happened to you there.

**Closed by bcoe** 2017-02-21 19:32 UTC
