### ISSUE TITLE
nyc trying to cover babel plugin even though it's excluded via config

### ISSUE THREAD

**Issue by NiGhTTraX** [istanbuljs/nyc#581] opened 2017-05-26 12:13 UTC
In a project that uses `babel-istanbul` and `babel-register` AND a custom babel plugin, nyc instruments the custom plugin even though it's in a folder excluded from coverage via `.nycrc:exclude`.

## Expected Behavior

100% coverage on src/foobar.js and nothing else because nyc is set to [exclude](https://github.com/NiGhTTraX/nyc-exclude-bug/blob/adb30c42ae3991d359a8f758ec52743825630023/.nycrc#L6) the `tests/` folder which includes the [babel-plugin](https://github.com/NiGhTTraX/nyc-exclude-bug/blob/adb30c42ae3991d359a8f758ec52743825630023/tests/babel-plugin.js) defined in [.babelrc](https://github.com/NiGhTTraX/nyc-exclude-bug/blob/adb30c42ae3991d359a8f758ec52743825630023/.babelrc#L6).

## Observed Behavior

![image](https://cloud.githubusercontent.com/assets/485061/26493876/41900050-421c-11e7-9f51-fc85d85c2259.png)

![image](https://cloud.githubusercontent.com/assets/485061/26493883/49d460b2-421c-11e7-9e34-5f43286bcdf4.png)

## Bonus Points! Code (or Repository) that Reproduces Issue

https://github.com/NiGhTTraX/nyc-exclude-bug

```
{
  "include": [
    "src/**/*.js"
  ],
  "exclude": [
    "tests/**/*.js"
  ],
  "all": true,

  "sourceMap": false,
  "instrument": false,

  "reporter": ["html"],
  "report-dir": "tests/unit/results/coverage",

  "lines": 100,
  "branches": 100,
  "check-coverage": true
}
```

## Forensic Information

**Operating System:** Ubuntu 16.04
**Environment Information:**

Node: v6.9.5
npm: 3.10.10

**Comment by bcoe** [comment] 2017-07-30 19:29
@NiGhTTraX thanks for the great reproduction, and sorry for the slow reply have been trying to gradually catch up on old GitHub issues.

I did a tiny bit of digging using your example repo, and the issue seems to be an interaction between the exclude rules and he `--all` functionality. My hunch is that the walk of files that takes place during the `--all` step isn't having the include and exclude rules applied.

If you feel like contributing to the project, this is probably a pretty straight forward fix; I think it will be in `nyc/index.js`.

**Comment by NiGhTTraX** [comment] 2017-08-31 19:19
So I found the real problem: the plugin is instrumented by `babel-plugin-istanbul` when it's required by Babel while transpiling a source file with `babel-register`. Deep breath. Here's how it happens:

1. `if (config.all) nyc.addAllFiles()` - entry point for when `all: true`
1. `glob.sync(pattern, {cwd: dir, nodir: true, ignore: this.exclude.exclude})` - this correctly excludes the plugin; let's assume that it emits `todo.jsx` for now
1. `NYC.prototype._readTranspiledSource` requires the source file
1. `babel-register` handler will pick the require and compile it
1. Doing so it will apply the plugins in `.babelrc` over it
1. `my-custom-babel-plugin` is part of `.babelrc` so Babel will fetch it by doing a `require` call
1. `babel-register` sees that require and tries to compile the plugin
1. It will again use the plugins in `.babelrc`
1. At this point `babel-plugin-istanbul` will instrument `my-custom-babel-plugin`
1. That instrumented plugin will report coverage to nyc

So yeah, not really a nyc bug. Maybe `babel-plugin-istanbul` could read the same excludes and bail out if it's attempting to instrument an excluded file?

#649 would work around the problem, but I'd like to have the code not emit coverage reports in case other tools will read it instead of nyc.

A foolproof workaround is to put the plugin in a separate folder and add a `.babelrc` there that removes `babel-plugin-istanbul`. This is the [solution](https://github.com/NiGhTTraX/react-test-buffet/commit/8de4d2a553b86c0afcb2f5fd4d12967482e4623b) I've went with and it's working as expected. I had to duplicate the `.babelrc` file, but eh...

**Closed** 2017-09-05 00:27 UTC
Labels: bug, Great First Contribution, triaged
