### ISSUE TITLE
NYC hanging when updating mocha to 4.0.1

### ISSUE THREAD

**Issue by michaeldfallen** [istanbuljs/nyc#688] opened 2017-10-12 09:28 UTC
## Expected Behavior

Running `yarn test` executes tests and reports coverage at the end.

## Observed Behavior

Mocha completes it's test suites and then all output hangs. After 10mins travis fails the build.

## Bonus Points! Code (or Repository) that Reproduces Issue

https://github.com/hmcts/one-per-page/pull/48

## Forensic Information

Environment is repeatable by cloning https://github.com/hmcts/one-per-page and running `make`. That will drop you in a shell ready to replicate by running yarn test.

**Operating System:** Ubuntu based docker image - `Linux c1cc44f7cb4a 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 GNU/Linux`
**Environment Information:** https://gist.github.com/michaeldfallen/35457b47f8da03d54e7b30a4a30e9645

**Comment by TheAdamizer** [comment] 2017-10-24 05:42
Hi @michaeldfallen This is due to [a change](https://github.com/mochajs/mocha/issues/2879) to Mocha's exit behavior in version 4.  As discussed [here](https://github.com/mochajs/mocha/issues/3044) a workaround is to simply add `--exit` to the mocha execution in your `package.json` or what have you like so:
```
"scripts": {
  "tests": "nyc mocha --exit"
},
```

**Comment by vinteo** [comment] 2017-11-15 04:23
Closing as the issue is with mocha and workaround has been provided.

**Closed by vinteo** 2017-11-15 04:23 UTC

**Comment by basickarl** [comment] 2018-01-26 09:29
This information SHOULD be added to the documentation.
