### ISSUE TITLE
`--all` flag fails to include tested files, sometimes displays no files at all

### ISSUE THREAD

**Issue by ralphholzmann** [istanbuljs/nyc#849] opened 2018-05-31 17:56 UTC
## Expected Behavior
`nyc -a` should list all tested and untested files.

## Observed Behavior
`nyc -a` only lists **untested** files when called against mocha directly. Tested files are not listed.

`nyc -a` lists *no files* when called against `npm test`.

## Bonus Points! Code (or Repository) that Reproduces Issue
https://github.com/ralphholzmann/instanbul-bug

## Forensic Information

**Operating System:** the operating system you observed the issue on.
Mac OS

**Environment Information:**

https://gist.github.com/ralphholzmann/aa66651e742688942556b42c690b5256

**Comment by paulsmirnov** [comment] 2018-06-07 11:08
Cannot reproduce on Windows with nyc 11.8.0:

```
D:\...\instanbul-bug>npm run test:coverage                       
                                                                                         
> istanbul-bug@1.0.0 test:coverage D:\...\instanbul-bug          
> cross-env NODE_ENV=test nyc -a npm test                                                
                                                                                         
                                                                                         
> istanbul-bug@1.0.0 test D:\...\instanbul-bug                   
> mocha --require @babel/register                                                        
                                                                                         
                                                                                         
                                                                                         
  Tested file                                                                            
    √ adds one                                                                           
                                                                                         
                                                                                         
  1 passing (32ms)                                                                       
                                                                                         
----------------|----------|----------|----------|----------|-------------------|        
File            |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |        
----------------|----------|----------|----------|----------|-------------------|        
All files       |      100 |      100 |      100 |      100 |                   |        
 tested-file.js |      100 |      100 |      100 |      100 |                   |        
----------------|----------|----------|----------|----------|-------------------|        
                                                                                         
D:\...\instanbul-bug>npm run test:coverage2                      
                                                                                         
> istanbul-bug@1.0.0 test:coverage2 D:\...\instanbul-bug         
> cross-env NODE_ENV=test nyc -a mocha --require @babel/register                         
                                                                                         
                                                                                         
                                                                                         
  Tested file                                                                            
    √ adds one                                                                           
                                                                                         
                                                                                         
  1 passing (39ms)                                                                       
                                                                                         
------------------|----------|----------|----------|----------|-------------------|      
File              |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |      
------------------|----------|----------|----------|----------|-------------------|      
All files         |       50 |      100 |       50 |       50 |                   |      
 tested-file.js   |      100 |      100 |      100 |      100 |                   |      
 untested-file.js |        0 |      100 |        0 |        0 |                 1 |      
------------------|----------|----------|----------|----------|-------------------|
```

**Comment by paulsmirnov** [comment] 2018-06-07 11:14
However, `"nyc": {..., "all": true}` option in `package.json` doesn't work and that is strange to me (as it is documented in README).

**Comment by coreyfarrell** [comment] 2018-06-19 16:08
Please see https://github.com/istanbuljs/nyc#require-additional-modules.

I am able to see your issue, but I'm able to fix it by moving `--register @babel/core`.  Your current package.json has:
```json
{
  "scripts": {
    "test": "mocha --require @babel/register",
    "test:coverage": "NODE_ENV=test nyc -a npm test",
    "test:coverage2": "NODE_ENV=test nyc -a mocha --require @babel/register"
  }
}
```
According to the documentation this would be more correct:
```json
{
  "scripts": {
    "test": "mocha --require @babel/register",
    "test2": "mocha",
    "test:coverage": "NODE_ENV=test nyc -a --require @babel/register npm run test2",
    "test:coverage2": "NODE_ENV=test nyc -a mocha --require @babel/register"
  }
}
```

Important detail is that you have to pass `--require @babel/register` to nyc, not mocha.  It doesn't seem to matter when mocha is the direct subprocess of nyc, but it does seem to matter when working directly (like nyc -> npm -> mocha).  I'm not sure if issues might happen from running `NODE_ENV=test nyc -a --require @babel/register npm test` (where `--require @babel/register` is passed to nyc and mocha), that is why my exist shows a `test2 script which excludes it.

**Comment by coreyfarrell** [comment] 2018-06-19 16:10
Another unrelated note, babel-plugin-istanbul is currently written against babel 6.  Using it in babel 7 doesn't seem to be causing any issues but I still wanted to mention.  I have a PR to switch it to use babel 7 but that is not yet merged and will result in a semver-major version bump.

**Comment by brunapereira** [comment] 2018-07-09 23:22
Thanks, @coreyfarrell 
```
"test": "mocha --recursive --require babel-core/register",
"test:coverage": "nyc npm test"
```
I was facing this issue with the scripts above. When I changed it to 
```
"test": "mocha --recursive --require babel-core/register",
"test:coverage": "nyc --require babel-core/register mocha --recursive"
```
the library didn't show inconsistency anymore :)

**Closed** 2019-01-26 16:32 UTC
Labels: wontfix
